name: "Vulnerability Scan"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'

jobs:
  analyze:
    name: Anchore scan
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: get latest config-api build
      run: |
        version=$(mvn org.apache.maven.plugins:maven-help-plugin:3.1.0:evaluate -Dexpression=project.version -q -DforceStdout)
        echo "$version"
        wget https://ox.gluu.org/maven/org/gluu/gluu-admin-ui-app//$version/gluu-admin-ui-app-$version.jar
        
    # Runs vulnerability scan.
    - uses: anchore/scan-action@v2
      id: scan
      with:
        path: "."
        acs-report-enable: true
    - name: upload Anchore scan SARIF report
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: results.sarif

